### ISSUE TITLE
Adding a search bar on the results page

### ISSUE THREAD

**Issue by jai-dewani** [utkarsh-raj/umusic#12]
Adding this feature will help users to search again without going back to the root page.
Maybe the same search bar can be just implemented/copied on the top of the results page

**Comment by utkarsh-raj** [comment]
Sounds right. Would you want to take this up @jai-dewani ?

**Comment by jai-dewani** [comment]
Sure I would love to, but if you are going to port this to vue.js will all the changes we make to UI will be useless or they can be recycled in vue.js?

**Comment by utkarsh-raj** [comment]
We'll do out best to reuse the existing code as components, but don't let it keep you from working on this!
